### ISSUE TITLE
Create a Dump of Input/Output Data?

### ISSUE THREAD

**Issue by Ecksters** [raphnet/pj64raphnetraw#2]
I'm working on an HLE implementation of the Hey You, Pikachu! controller, and I bought your adapter for testing, as it's the first hardware that can use the VRU as far as I'm aware.

I'm wondering what changes I would need to make to the source to create dumps of when the game sends data to the VRU, and when the VRU sends input back, this way I can figure out exactly how the game is communicating with the device to emulate it.

**Comment by Ecksters** [comment]
I suppose more to the point, how do I enable the built in Debug for the Ports 1 and 4 build?

I changed the Makefile line to:
	$(CC) $(CFLAGS) -c $^ -o $@ -DPORTS_1_AND_4 -D_DEBUG

But I'm not seeing where I can read the output.

**Comment by raphnet** [comment]
When I use the _DEBUG code, it is always with mupen64 under Linux.. (this file is shared between the PJ64 and mupen64plus versions of the plugin). With project64 under Windows I'm sorry but I have no idea where stdout goes therefore do not know where the output ends up.

I guess you could duplicate the DebugMessage mechansim (see plugin_front.c) to dump directly to a file. Or rewrite the existing debugging functions to output using DebugMessage instead of printf...
